## 基本配置
server.port: 9700
spring:
  application:
    name: sun8min-sso
    version: ${project.version}

  ## thymeleaf配置
  thymeleaf.cache: false
  ## devtools配置
  devtools.restart.enabled: false

## CAS配置
cas:
  server:
    port: 8081
    host:
      ## CAS服务地址
      url: http://localhost:${cas.server.port}/cas
      ## CAS服务登录地址
      login_url: ${cas.server.host.url}/login
      ## CAS服务登出地址
      logout_url: ${cas.server.host.url}/logout?service=${app.server.host.url}
## 应用访问地址
app.server.host.url: http://localhost:${server.port}
## 应用登录地址
app.login.url: /login
## 应用登出地址
app.logout.url: /logout