## \u57FA\u672C\u914D\u7F6E
server.port: 9700
spring:
  application:
    name: sun8min-sso
    version: ${project.version}

  ## thymeleaf\u914D\u7F6E
  thymeleaf.cache: false
  ## devtools\u914D\u7F6E
  devtools.restart.enabled: false

## CAS\u914D\u7F6E
cas:
  server:
    port: 8081
    host:
      ## CAS\u670D\u52A1\u5730\u5740
      url: http://localhost:${cas.server.port}/cas
      ## CAS\u670D\u52A1\u767B\u5F55\u5730\u5740
      login_url: ${cas.server.host.url}/login
      ## CAS\u670D\u52A1\u767B\u51FA\u5730\u5740
      logout_url: ${cas.server.host.url}/logout?service=${app.server.host.url}
## \u5E94\u7528\u8BBF\u95EE\u5730\u5740
app.server.host.url: http://localhost:${server.port}
## \u5E94\u7528\u767B\u5F55\u5730\u5740
app.login.url: /login
## \u5E94\u7528\u767B\u51FA\u5730\u5740
app.logout.url: /logout