## 基本配置
server.port: 9600
spring:
  application:
    name: sun8min-seckill
    version: 2.1.0

  ## thymeleaf配置
  thymeleaf.cache: false
  ## devtools配置
  devtools.restart.enabled: false

## Eureka 配置
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

## zookeeper 配置
zookeeper.port: 2181

## dubbo 配置（-1表示随机端口）
dubbo:
  registry.address: zookeeper://127.0.0.1:${zookeeper.port}
  application.name: ${spring.application.name}

## 服务版本号
service.version: ${spring.application.version}

## sso配置
server:
  host:
    # CAS服务地址
    url: http://cas.server.com:8080/cas
    # CAS服务登录地址
    login_url: ${server.host.url}/login
    # CAS服务登出地址
    logout_url: ${server.host.url}/logout?service=${app.server.host.url}
app:
  # 应用访问地址
  server.host.url: http://www.app1.com:${server.port}
  # 应用登录地址
  login.url: /login
  # 应用登出地址
  logout.url: /logout